apiVersion: apps/v1
kind: Deployment
metadata:
  name: clo835-assignment2-srsivagnanasundaram
spec:
  replicas: 3
  selector:
    matchLabels:
      app: clo835-assignment2-srsivagnanasundaram
  template:
    metadata:
      labels:
        app: clo835-assignment2-srsivagnanasundaram
    spec:
      containers:
        - name: clo835-assignment2-srsivagnanasundaram-container
          image: clo835-assignment2-srsivagnanasundaram:0.2
          ports:
            - containerPort: 8080
